
resources:
  repositories:
  - repository: self
    type: git
    ref: develop
jobs:
- job: Job_1
  displayName: Agent job 1
  pool: 
    name: LOGCORNER-POOL
  steps:
  - checkout: self
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'logcorner-edusync-speech'
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'logcorner-edusync-speech'
      customCommand: 'run build -- --output-path=./dist '
