apiVersion: apps/v1
kind: Deployment

metadata:
  name: front-end-deployment
  namespace: dev
  labels:
    run: front-end

spec:
  replicas: 1
  selector:
    matchLabels:
      run: front-end
  
  template:
    metadata:
      labels:
        run: front-end
    spec:
      containers:
      - name: front-end-container
        image: logcornerhub/logcorner-edusync-speech-front
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: "kubernetes"
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
    