apiVersion: apps/v1
kind: Deployment

metadata:
  name: speech-front-end-deployment
  namespace: dev
  labels:
    version: 1.0.0
    product: speech-front-end
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-front-end
      env: dev
  
  template:
    metadata:
      labels:
        app: speech-front-end
        env: dev
    spec:
      containers:
      - name: speech-front-end
        image: logcornerhub/logcorner-edusync-speech-front
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: "kubernetes"
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
    