apiVersion: v1
kind: Service
metadata:
  name: front-end-deployment
  namespace: dev
  labels:
    version: 1.0.0
    product: speech-front-end
    environment: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: speech-front-end
    env: dev