
version: '3.4'
services:
  logcorner.edusync.speech.front:
    container_name: logcorner.edusync.speech.front
    image: ${DOCKER_REGISTRY-}/logcorner-edusync-speech-front
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
       - configuration=${ENVIRONMENT}
    ports:
      - "4200:80"
      - "443:443"
    environment:
        NODE_ENV: ${ENVIRONMENT}
    networks:
      - speech_network

networks:
  speech_network:
    external:
      name: speech_network